#include "formreport.h"
#include "ui_formreport.h"
#include <QDate>

FormReport::FormReport(QWidget *parent) :
    QWidget(parent),
    ui(new Ui::FormReport)
{
    ui->setupUi(this);
    html = QString("<body>"
                   "<p>Отчет за _______</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                  " <p>&nbsp;</p>"
                  " <p>&nbsp;</p>"
                  " <p>&nbsp;</p>"
                  " <p>&nbsp;</p>"
                  " <p>&nbsp;</p>"
                  " <p>&nbsp;</p>"
                  " <p>&nbsp;</p>"
                  " <p>&nbsp;</p>"
                  " <p>&nbsp;</p>"
                  " <p>&nbsp;</p>"
                  " <p>&nbsp;</p>"
                  " <p>&nbsp;</p>"
                  " <p>&nbsp;</p>"
                  " <p>&nbsp;</p>"
                  " <p>&nbsp;</p>"
                  " <p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p>&nbsp;</p>"
                   "<p style=\"text-align:right\">Отчет выполнен</p>"
                   "<p style=\"text-align:right\">&nbsp;</p>"
                   "<p style=\"text-align:right\"><u>__________</u>&nbsp;Подпись</p>"
                 "</body>").arg(QDate::currentDate().toString("dd.MM.yyyy"));
    ui->html->setText(html);
    doc.setHtml(html);

}

void FormReport::callSignal(QString filter)
{
    emit signalSendToServer(data);
}

FormReport::~FormReport()
{
    delete ui;
}

void FormReport::slotGetData(QDataStream &in)
{

}

void FormReport::on_pushButton_clicked()
{
    QPrinter printer(QPrinter::HighResolution);
    printer.setOutputFormat(QPrinter::PdfFormat);
    printer.setOutputFileName(QString("отчет за" + QDate::currentDate().toString("dd.MM.yyyy")) + ".pdf");
    doc.print(&printer);

}

