DROP FUNCTION ADDSERVICES;
CREATE OR REPLACE FUNCTION ADDSERVICES(_ID INT, _DATA TEXT[], _IDE INT) RETURNS TEXT AS $$
DECLARE _MSG TEXT;
SIZE_ARRAY INT:=ARRAY_LENGTH(_DATA, 1);
I INT:=1;
_IDR INT;
BEGIN
	BEGIN
	SELECT IDROOM INTO _IDR FROM CHECKIN WHERE IDCHECKIN = _ID;
	
	WHILE I <= SIZE_ARRAY LOOP
		IF EXISTS(SELECT * FROM LIVINGSERVICE WHERE IDCHECKIN=_ID AND TYPESERVICE = _DATA[I]) THEN
		 UPDATE LIVINGSERVICE SET NUM = NUM + 1 WHERE IDCHECKIN=_ID AND TYPESERVICE = _DATA[I];
		ELSE INSERT INTO LIVINGSERVICE (TYPESERVICE, IDCHECKIN, NUM) VALUES (_DATA[I], _ID, 1);
		END IF;
		INSERT INTO WORKHOTEL (IDEMPLOYEE, IDROOM, NAMEWORK, TIME) VALUES(_IDE, _IDR, _DATA[I], CURRENT_DATE);
		I:=I+1;
	END LOOP;
	EXCEPTION WHEN OTHERS THEN
	GET STACKED DIAGNOSTICS
		_MSG:=MESSAGE_TEXT;
		RETURN _MSG;
	END;
	RETURN 'Успешно';
END; $$ LANGUAGE PLPGSQL;


SELECT *
FROM CHECKIN;


SELECT *
FROM LIVINGSERVICE
WHERE IDCHECKIN = 32
	SELECT ADDSERVICES(32,'{"Будильник"}')
	
	SELECT * FROM showWorkInHotel(CURRENT_DATE)